### ISSUE TITLE
Session Feedback

### ISSUE THREAD

**Issue by denisaburesin** [SAP-samples/ui5-exercises-codejam#16]
Thanks for taking a couple of minutes to give feedback, which will help me improve for next time. **Before doing anything else, hit the green button "Submit new issue" right now to save this issue content, rather than try to complete the feedback in this raw form.** Then go through the questions and mark a single checkbox for each, to represent your answer. Finally, in the empty comment box below this one, please describe what you liked and what you didn't like.

**How experienced were you with web development in general before this session?**

- [ ] Didn't know what HTML is
- [ ] Heard about HTML/CSS/JavaScript, but never developed a web app
- [X] Used HTML/CSS/JavaScript before, but never developed a complete web app on my own
- [ ] Developed one or more (smaller) web app(s) on my own
- [ ] I am a very experienced web developer

**How experienced were you with UI5 before this session?**

- [ ] Didn't know what UI5 was
- [ ] Heard about UI5, but never developed a UI5 app
- [X] Used UI5 before, but never developed a complete UI5 app on my own
- [ ] Developed one or more (smaller) UI5 app(s) on my own
- [ ] I am [Peter Muessig](https://twitter.com/pmuessig), or at least very experienced

**How do you feel about UI5 now (after this session)?**

- [ ] Don't know what UI5 is
- [ ] Know what UI5 is, but don't know how develop a UI5 app
- [ ] Know how to use parts of it, but don't know how to built a complete application on my own
- [X] Know how to built a complete application on my own
- [ ] I am [Peter Muessig](https://twitter.com/pmuessig), or at least very experienced

**Did this session meet your expectations?**

- [ ] Not really
- [ ] Somewhat
- [ ] Mostly
- [X] Fully

**Was the time allotted to each exercise enough for you to work through them?**

- [ ] Not really
- [ ] Somewhat
- [ ] Mostly
- [X] Fully

**What did you think of the extra information (collapsable sections 💬) and explanations provided?**

- [ ] Too much information
- [ ] Didn't really read it, didn't really bother me though
- [X] Found it helpful as context and background

**How did you find the way we all moved at the same pace through the exercises?**

- [ ] Would have preferred to go through them on my own at my own speed
- [ ] Didn't mind, no strong feelings either way
- [X] Found it useful to keep pace and discuss the exercise questions, and reflect

**Which development environment(s) did you use?**

- [ ] SAP Business Application Studio
- [X] Code editor on my local machine
- [ ] Devcontainer

If you have time, please add a comment below to write free-form what you liked and what you disliked about the session. Thank you!

I really enjoyed this training and will try to go through the whole learning material by my own.

**Comment by nicoschoenteich** [comment]
Hi @denisaburesin, thank you for the feedback and attending the CodeJam. Looking forward to next time! Best, Nico
