### ISSUE TITLE
Session Feedback

### ISSUE THREAD

**Issue by SvenVerbeek** [SAP-samples/ui5-exercises-codejam#26]
Thanks for taking a couple of minutes to give feedback, which will help me improve for next time. **Before doing anything else, hit the green button "Submit new issue" right now to save this issue content, rather than try to complete the feedback in this raw form.** Then go through the questions and mark a single checkbox for each, to represent your answer. Finally, in the empty comment box below this one, please describe what you liked and what you didn't like.

**How experienced were you with web development in general before this session?**

- [ ] Didn't know what HTML is
- [ ] Heard about HTML/CSS/JavaScript, but never developed a web app
- [ ] Used HTML/CSS/JavaScript before, but never developed a complete web app on my own
- [x] Developed one or more (smaller) web app(s) on my own
- [ ] I am a very experienced web developer

**How experienced were you with UI5 before this session?**

- [ ] Didn't know what UI5 was
- [x] Heard about UI5, but never developed a UI5 app
- [ ] Used UI5 before, but never developed a complete UI5 app on my own
- [ ] Developed one or more (smaller) UI5 app(s) on my own
- [ ] I am [Peter Muessig](https://twitter.com/pmuessig), or at least very experienced

**How do you feel about UI5 now (after this session)?**

- [ ] Don't know what UI5 is
- [ ] Know what UI5 is, but don't know how develop a UI5 app
- [ ] Know how to use parts of it, but don't know how to built a complete application on my own
- [x] Know how to built a complete application on my own
- [ ] I am [Peter Muessig](https://twitter.com/pmuessig), or at least very experienced

**Did this session meet your expectations?**

- [ ] Not really
- [ ] Somewhat
- [ ] Mostly
- [x] Fully

**Was the time allotted to each exercise enough for you to work through them?**

- [ ] Not really
- [ ] Somewhat
- [ ] Mostly
- [x] Fully

**What did you think of the extra information (collapsable sections 💬) and explanations provided?**

- [ ] Too much information
- [ ] Didn't really read it, didn't really bother me though
- [x] Found it helpful as context and background

**How did you find the way we all moved at the same pace through the exercises?**

- [ ] Would have preferred to go through them on my own at my own speed
- [x] Didn't mind, no strong feelings either way
- [ ] Found it useful to keep pace and discuss the exercise questions, and reflect

**Which development environment(s) did you use?**

- [ ] SAP Business Application Studio
- [x] Code editor on my local machine
- [ ] Devcontainer

If you have time, please add a comment below to write free-form what you liked and what you disliked about the session. Thank you!

**Comment by SvenVerbeek** [comment]
As something that came to mind after the session:
During the testing fase of the search functionality, it seemed that every keystroke of the keyboard triggered an api call to the database.
In an api-cost based environment where you can have x amount of messages a month, which will be a big part of the scope of SAP in the future with Cloud based applications, would this mean that every search keystroke is to be considered an api call and thus a 'message'? 

If that is the case then how would you tackle this issue? Since you wouldn't want to waste your precious, available messages on 'stupid' keystrokes in a search functionality.

If it's not the case that it consumes messages quota, then I'd also like to know how efficient the loading of this data, in a database set with thousands of records, would perform if every keystroke (or even the loading of the data itself on init) would trigger a new call to the backend. 

Thanks,

**Comment by nicoschoenteich** [comment]
Hi @SvenVerbeek,
Interesting question. Indeed, we [listened](https://github.com/SAP-samples/ui5-exercises-codejam/blob/main/bookshop/finished-webapp/view/App.view.xml#LL12C42-L12C52) to the [`liveChange`](https://ui5.sap.com/#/api/sap.m.SearchField%23events) event of the `SearchField`, which triggers an API call on every keystroke. However, this is optional - we could also listen for the `change` event, which only gets fired when the user hits enter or clicks the little search icon. I opted for the `liveChange` in this case solely because I think it provides a better user experience.
To your second point: The efficient querying and loading of data is handled by OData and HANA Cloud internally - nothing the application developer has to implement themself.
Thanks for attending the CodeJam and leaving feedback.
Looking forward to next time!
Best, Nico
