### ISSUE TITLE
Semicolons or not?

### ISSUE THREAD

**Issue by tobiashofmann** [SAP-samples/ui5-exercises-codejam#7]
The JavaScript code does not contain semicolons (e.g. https://github.com/SAP-samples/ui5-exercises-codejam/tree/main/chapters/chapter03)

While this is allowd and OK, there are linters in use at companies that might require a semicolon. If the CodeJam app is used there, the linter might throw errors. Default BAS configuration is not marking the missing semicolons. 

What do you think? Adding semicolons or not? Or give hints to companies where the linter is configured to throw a warning that this is a linter config "issue"?

**Comment by nicogeburek** [comment]
Interesting point. I also thought about generally covering the topic of linters a little. Maybe a short disclaimer in this repo would do the job. What do you think?

**Comment by nicoschoenteich** [comment]
I am a minimalist, so I decided to not use semicolons ;-)
